using Novolis.Documents;
using Novolis.Documents.Skia;

var outDir = Path.GetFullPath(Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
    ".novolis",
    "artifacts",
    "hello-document"));
Directory.CreateDirectory(outDir);
var pdfPath = Path.Combine(outDir, "hello-document.pdf");

var document = new PagedDocument
{
    Meta = new DocumentMeta
    {
        Title = "Hello Document",
        Subtitle = "novolis-documents dogfood",
        Author = "Novolis",
    },
    Setup = new PageSetup
    {
        Trim = TrimPresets.Inch6x9,
        Margin = TrimPresets.DefaultMargin,
    },
    Typography = new Typography(),
    IncludeCover = true,
    IncludeToc = true,
    Header = new RunningChrome { Template = "{title}" },
    Footer = new RunningChrome { Template = "{page}" },
    Body =
    [
        new HeadingBlock { Level = 1, Text = "Section One" },
        new ParagraphBlock
        {
            Text = "This PDF was generated by Novolis.Documents.Skia using a one-column layout. " +
                   "Cover, optional TOC, H1 breaks, and running chrome are in scope; tables and fluent layout are not.",
        },
        new SceneBreakBlock(),
        new ParagraphBlock { Text = "A second paragraph after a scene break." },
        new HeadingBlock { Level = 1, Text = "Section Two" },
        new ParagraphBlock { Text = "Second section opens on a fresh page when prior content exists." },
    ],
};

DocumentPdf.Write(document, pdfPath);
Console.WriteLine($"Wrote {pdfPath} ({new FileInfo(pdfPath).Length} bytes)");
return 0;
