using System.Text;
using Novolis.Documents;
using Novolis.Documents.Skia;

var outDir = Path.GetFullPath(Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
    ".novolis",
    "artifacts",
    "hello-document"));
Directory.CreateDirectory(outDir);
var pdfPath = Path.Combine(outDir, "hello-document.pdf");

static string Lorem(int words)
{
    ReadOnlySpan<string> corpus =
    [
        "the", "river", "ran", "cold", "through", "Duckville", "harbor", "lights", "winked", "across",
        "the", "strait", "while", "freight", "bells", "marked", "the", "hour", "and", "spray", "bit",
        "the", "quay", "stones", "Captain", "Rook", "checked", "the", "manifest", "twice", "then",
        "folded", "the", "chart", "into", "his", "coat", "as", "fog", "settled", "low", "over",
        "the", "channel", "markers", "and", "the", "tide", "turned", "toward", "the", "open", "reach",
    ];
    var parts = new string[words];
    for (var i = 0; i < words; i++)
        parts[i] = corpus[i % corpus.Length];
    var text = string.Join(' ', parts);
    return char.ToUpperInvariant(text[0]) + text[1..] + ".";
}

var document = new PagedDocument
{
    Meta = new DocumentMeta
    {
        Title = "Duckville Harbor",
        Subtitle = "A NearSol Freighter Chronicle",
        Series = "Calypso Tramp Stories",
        Author = "Novolis",
        Rights = "© 2026 Novolis-Platform. All rights reserved.",
    },
    Setup = new PageSetup
    {
        // Matches ManuscriptPrintSettings: 6×9, L0.65 / R0.55 / V0.75
        Trim = TrimPresets.Inch6x9,
        Margin = TrimPresets.DefaultMargin,
    },
    Typography = new Typography
    {
        BodyFontFamily = "Georgia",
        BodyFontSizePt = 11f,
        LineHeight = 1.42f,
        ParagraphSpacingPt = 8f,
        H1SizePt = 19f,
        H2SizePt = 14f,
        H3SizePt = 12f,
        SceneBreakSizePt = 22f,
    },
    IncludeCover = true,
    IncludeToc = true,
    SuppressHeaderOnH1Open = true,
    Header = new RunningChrome { Template = "{title}", FontSizePt = 9f },
    Footer = new RunningChrome { Template = "{page}", FontSizePt = 9f },
    Last = new LastPage
    {
        Lines =
        [
            "End of sample.",
            "Generated by Novolis.Documents.Skia for dogfood verification.",
        ],
    },
    Body =
    [
        new HeadingBlock { Level = 1, Text = "Chapter 1 - Arrival" },
        new ParagraphBlock { Text = Lorem(220) },
        new HeadingBlock { Level = 2, Text = "Quay-side" },
        new ParagraphBlock { Text = Lorem(180) },
        new SceneBreakBlock(),
        new ParagraphBlock { Text = Lorem(160) },
        new HeadingBlock { Level = 1, Text = "Chapter 2 - Manifest" },
        new ParagraphBlock { Text = Lorem(240) },
        new HeadingBlock { Level = 2, Text = "Bonded cargo" },
        new ParagraphBlock { Text = Lorem(200) },
        new HeadingBlock { Level = 3, Text = "Lien notes" },
        new ParagraphBlock { Text = Lorem(120) },
        new SceneBreakBlock(),
        new ParagraphBlock { Text = Lorem(190) },
        new HeadingBlock { Level = 1, Text = "Chapter 3 - Departure" },
        new ParagraphBlock { Text = Lorem(260) },
        new ParagraphBlock { Text = Lorem(200) },
    ],
};

DocumentPdf.Write(document, pdfPath);
var bytes = File.ReadAllBytes(pdfPath);
var ascii = Encoding.ASCII.GetString(bytes);
var pageMarkers = 0;
for (var i = 0; i < ascii.Length - 10; i++)
{
    if (ascii.AsSpan(i).StartsWith("/Type /Page", StringComparison.Ordinal)
        && !ascii.AsSpan(i).StartsWith("/Type /Pages", StringComparison.Ordinal))
        pageMarkers++;
}

Console.WriteLine(pdfPath);
Console.WriteLine($"Bytes: {bytes.Length}");
Console.WriteLine($"PDF /Type /Page markers: {pageMarkers}");
return pageMarkers >= 5 ? 0 : 1;
