using System.Text;
using Novolis.Documents;
using Novolis.Documents.Skia;

var outDir = Path.GetFullPath(Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
    ".novolis",
    "artifacts",
    "hello-document"));
Directory.CreateDirectory(outDir);
var pdfPath = Path.Combine(outDir, "hello-document.pdf");

static string Lorem(int words)
{
    ReadOnlySpan<string> corpus =
    [
        "the", "river", "ran", "cold", "through", "Duckville", "harbor", "lights", "winked", "across",
        "the", "strait", "while", "freight", "bells", "marked", "the", "hour", "and", "spray", "bit",
        "the", "quay", "stones", "Captain", "Rook", "checked", "the", "manifest", "twice", "then",
        "folded", "the", "chart", "into", "his", "coat", "as", "fog", "settled", "low", "over",
        "the", "channel", "markers", "and", "the", "tide", "turned", "toward", "the", "open", "reach",
    ];
    var parts = new string[words];
    for (var i = 0; i < words; i++)
        parts[i] = corpus[i % corpus.Length];
    var text = string.Join(' ', parts);
    return char.ToUpperInvariant(text[0]) + text[1..] + ".";
}

var document = Document.Create("Duckville Harbor")
    .Meta(m => m
        .Subtitle("A NearSol Freighter Chronicle")
        .Series("Calypso Tramp Stories")
        .Author("Novolis")
        .Publisher("Novolis-Platform")
        .Subject("Tramp freighter fiction")
        .Keywords("calypso", "harbor", "nearSol")
        .Language("en")
        .Version("1.0")
        .Date(new DateOnly(2026, 8, 8))
        .Rights("© 2026 Novolis-Platform. All rights reserved."))
    .Page(p => p
        .Trade6x9()
        .Header("{title}", 9f)
        .Footer("{page} / {pages}", 9f)
        .Chrome(c => c.PageNumbersOnFrontMatter()))
    .Watermark(w => w.Text("SAMPLE").Color(DocumentColor.Red).Opacity(0.10f).On(WatermarkPages.All))
    .SuppressHeaderOnLevel1Open()
    .Body(b => b
        .First(f => f.Lines("Trade paperback sample", "Printed via Novolis.Documents.Skia"))
        .Content(c => c
            .Toc()
            .Chapter("Chapter 1 - Arrival", ch => ch
                .Paragraph(Lorem(180))
                .H2("Quay-side")
                .Paragraph(Lorem(120))
                .Table(t => t
                    .Headers("Cargo", "Tons", "Bond")
                    .Row("Grain", "120", "Yes")
                    .Row("Timber", "80", "No")
                    .Row("Ore", "45", "Yes")
                    .Rules(TableRuleStyle.Horizontal)
                    .HeaderBackground())
                .SceneBreak()
                .Paragraph(Lorem(100)))
            .Chapter("Chapter 2 - Manifest", ch => ch
                .Paragraph(Lorem(160))
                .H2("Bonded cargo")
                .Paragraph(Lorem(120)))
            .Chapter("Chapter 3 - Departure", ch => ch
                .Paragraph(Lorem(180))))
        .Last(l => l
            .Title("Colophon")
            .Lines(
                "End of sample.",
                "Generated by Novolis.Documents.Skia for dogfood verification.")
            .Blocks(blocks => blocks.Table(t => t
                .Headers("Item", "Value")
                .Row("Engine", "Documents.Skia")
                .Row("Trim", "6×9 in")
                .Row("Margins", "print (0.75 / 0.5 / 0.5 / 0.65)")
                .Rules(TableRuleStyle.Horizontal)
                .HeaderBackground()))))
    .Build();

DocumentPdf.Write(document, pdfPath);
var bytes = File.ReadAllBytes(pdfPath);
var ascii = Encoding.ASCII.GetString(bytes);
var pageMarkers = 0;
for (var i = 0; i < ascii.Length - 10; i++)
{
    if (ascii.AsSpan(i).StartsWith("/Type /Page", StringComparison.Ordinal)
        && !ascii.AsSpan(i).StartsWith("/Type /Pages", StringComparison.Ordinal))
        pageMarkers++;
}

Console.WriteLine(pdfPath);
Console.WriteLine($"Bytes: {bytes.Length}");
Console.WriteLine($"PDF /Type /Page markers: {pageMarkers}");
return pageMarkers >= 5 && bytes.Length < 80_000 ? 0 : 1;
