using Novolis.Documents;
using Novolis.Documents.Skia;

var outDir = Path.GetFullPath(Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
    ".novolis",
    "artifacts",
    "hello-book"));
Directory.CreateDirectory(outDir);
var pdfPath = Path.Combine(outDir, "hello-book.pdf");

var book = new BookDocument
{
    Meta = new BookMeta
    {
        Title = "Hello Book",
        Subtitle = "novolis-documents dogfood",
        Author = "Novolis",
    },
    Setup = new PageSetup
    {
        Trim = TrimPresets.TradePaperback6x9,
        Margin = TrimPresets.DefaultBookMargin,
    },
    Typography = new Typography(),
    IncludeCover = true,
    IncludeToc = true,
    Header = new RunningChrome { Template = "{title}" },
    Footer = new RunningChrome { Template = "{page}" },
    Body =
    [
        new HeadingBlock { Level = 1, Text = "Chapter One" },
        new ParagraphBlock
        {
            Text = "This PDF was generated by Novolis.Documents.Skia using a one-column book layout. " +
                   "Cover, optional TOC, chapter breaks, and running chrome are in scope; tables and fluent layout are not.",
        },
        new SceneBreakBlock(),
        new ParagraphBlock { Text = "A second paragraph after a scene break." },
        new HeadingBlock { Level = 1, Text = "Chapter Two" },
        new ParagraphBlock { Text = "Second chapter opens on a fresh page when prior content exists." },
    ],
};

BookPdf.Write(book, pdfPath);
Console.WriteLine($"Wrote {pdfPath} ({new FileInfo(pdfPath).Length} bytes)");
return 0;
